---
# tasks file for user
- name: user
  block:
    - name: create group
      group:
        name: "{{ user_group }}"
      when: ansible_os_family != 'RedHat' and inventory_hostname not in groups.NFERX

    - name: create user
      user:
        name: "{{ user_name }}"
        group: "{{ user_group }}"
        groups: ["{{ user_group }}", 'sudo', 'adm']
        append: true
        shell: "/bin/bash"
      when: ansible_os_family != 'RedHat' and inventory_hostname not in groups.NFERX

    - name: create user RedHat
      user:
        name: "{{ user_name }}"
        group: "{{ user_group }}"
        groups: ["{{ user_group }}", 'adm']
        append: true
        shell: "/bin/bash"
      when: ansible_os_family == 'RedHat'

    - name: copy authorized_key
      authorized_key:
        user: "{{ user_name }}"
        key: "{{ lookup('file', user_key_file) }}"

    # - name: sudoers not in user_sudoers_exclude_server_group
    #   template:
    #     src: sudoers.j2
    #     dest: /etc/sudoers
    #     owner: root
    #     group: root
    #     mode: 0440
    #     backup: True
    #     validate: '/usr/sbin/visudo -cf %s'
    #   when: inventory_hostname not in groups.NFERX

    - name: sudoers in user_sudoers_exclude_server_group
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^{{ item }}'
        line: '{{ item }}'
        insertafter: EOF
        backup: True
        validate: '/usr/sbin/visudo -cf %s'
      loop:
        - 'Defaults !env_reset'
        - 'Defaults env_delete = "HOME"'
        - 'Defaults env_delete = "PS1"'
        - 'Defaults:{{ user_name }} !logfile, !syslog'
        - '{{ user_name }} ALL=(ALL) NOPASSWD: ALL'
      when: inventory_hostname in groups.NFERX

    - name: sudoers.d
      become: yes
      template:
        src: sudoers_user.j2
        dest: /etc/sudoers.d/{{ user_name }}
        owner: root
        group: root
        mode: 0440
        backup: True
        validate: '/usr/sbin/visudo -cf %s'
      when: inventory_hostname not in groups.NFERX

    # - name: sudoers.d
    #   template:
    #     src: sudoers_user.j2
    #     dest: /etc/sudoers.d/{{ user_name }}
    #     owner: root
    #     group: root
    #     mode: 0440
    #     backup: True
    #     validate: '/usr/sbin/visudo -cf %s'
    #   when: inventory_hostname not in groups.NFERX
  when: ansible_distribution != 'MacOSX'
